### ISSUE TITLE
未适配 Chrome 的自动深色主题

### ISSUE THREAD

**Issue by L33Z22L11** [EveSunMaple/Frosti#78]
这个问题是先前 #16 的延伸问题。

在 Chrome 120+ 版本上，如果设备使用深色模式而网页使用浅色模式，Chrome 会启用 [自动深色主题](https://developer.chrome.google.cn/blog/auto-dark-theme) 。在**移动端**可直接观察到网页颜色不符合预期，在电脑端可通过 `DevTools - Styles（样式）- 刷子图标（切换常见渲染仿真）` 启用自动深色主题来复现问题。

如此便可规避：

```css
:root, [data-theme-type="light"] {
    color-scheme: light dark; /* 其他选择器不应覆写此声明 */
}

[data-theme-type="dark"] {
    color-scheme: dark;
}
```

---

可以参阅我的 [深色模式开发的最佳实践](https://blog.zhilu.cyou/2025/dark-mode-guide) 一文，另外，希望 [前端字体二三事](https://blog.zhilu.cyou/2025/font-tips) 也能对你有所帮助。

另外，HTML 的元数据标签采取了 `<meta content="width=device-width,initial-scale=1" name="viewport">` 这种先 `content` 再 `name` 的形式，看起来不太合逻辑顺序，不知有何考量👀
